### ISSUE TITLE
Missing vec2 Object

### ISSUE THREAD

**Issue by CGBrown0451** [Technostalgic/MatterJS_Raycast#1]
The main function references a Vector2 object existing in the code, but it doesn't exist at all. I'm using the ES6 version of the code, but the ES5 version seems to have the same issue.

**Comment by jonahrosenblum** [comment]
I thought I was missing something too but it looks like the vec2 object is not included in these files.

**Comment by jonahrosenblum** [comment]
I created a pull request with the vec2 class, hope it works for you like it has for me.

**Comment by Technostalgic** [comment]
Woops! Sorry, don't know how I missed that. Should be fixed now!!
